sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - pip install pyflakes

script:
  - pyflakes packtivity
  - pip install -e '.[celery]' --process-dependency-links
  - cd tests && pytest && cd ..
  - 'echo "a_parameter: 10" > input.yml'
  - packtivity-run testspacks/noop-test.yml input.yml
#  - docker build -t lukasheinrich/packtivity .

