sudo: required

services:
  - docker

language: python
python:
  - '2.7'
  - '3.5'
install:
  - pip install pyflakes pytest pytest-cov python-coveralls
  - pip install --process-dependency-links -e '.[celery]'

script:
  - pyflakes packtivity
  - pytest --cov=packtivity -vv
  - packtivity-run tests/testspecs/noop-test.yml -p a_parameter=hello

after_success:
  - coveralls 

