sudo: required

services:
  - docker

language: python
python:
  - '2.7'

install:
  - pip install pyflakes pytest pytest-cov python-coveralls
  - pip install --process-dependency-links -e .

script:
  - pyflakes packtivity
  - pytest --cov=packtivity -vv
  - cd tests && pytest && cd ..
  - 'echo "a_parameter: 10" > input.yml'
  - packtivity-run testspacks/noop-test.yml input.yml

after_success:
  - coveralls 

